version: "3.9"

services:
  web:
    image: webdevops/php-apache-dev:8.0-alpine
    ports:
      - "4500:80"
    volumes:
      - ./www:/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8088:80"

volumes:
  www:
